services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      sope-ecommerce-backend-network:
        aliases:
          - 18.141.145.133

  api-product:
    image: ${DOCKER_IMAGE_SON}:${DOCKER_TAG}
    container_name: ${DOCKER_CONTAINER}
    env_file:
      - .env
    ports:
      - "${SERV_PORT}:${SERV_PORT}"
    depends_on:
      - redis
    networks:
      - sope-ecommerce-backend-network

networks:
  sope-ecommerce-backend-network:
    external: true
