services:
  api-product:
    image: ${DOCKER_IMAGE_SON}:${DOCKER_TAG}
    container_name: ${DOCKER_CONTAINER}
    env_file:
      - .env
    ports:
      - "${SERV_PORT}:${SERV_PORT}"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - sope-ecommerce-backend-network

networks:
  sope-ecommerce-backend-network:
    external: true
