services:
  api-product:
    image: hoangson3000/api-product:latest
    container_name: api-product
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=local 
    volumes:
      - ./application-local.yml:/app/src/main/resources/application-local.yml:ro
      - ./.env.properties:/app/.env.properties:ro
    networks:
      - customer-network

networks:
  customer-network:
    external: true
