services:
  postgres:
    image: postgres:latest
    container_name: sope-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: sope
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - sope-network

  redis:
    image: redis:latest
    container_name: sope-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - sope-network


  server:
#    build:
#      context: .
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    container_name: sope-server
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - sope-network


networks:
  sope-network:
    driver: bridge


volumes:
  postgres_data:
    driver: local
#  docker network create sope-network
