spring:
  application:
    name: sope ecommerce backend

  profiles:
    active: dev

  jwt:
    secret: bWVzc2lidWN1cm9uYWxkb2hhaGFoYWhhaGFoYWhhaGE=
    expiration: 3600000

  datasource:
    url: jdbc:postgresql://localhost:5432/sope
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

server:
  port: 8082
  tomcat:
    max-part-count: 50
    max-part-header-size: 2048

api:

cloudinary:
  cloud-name: dybo8zd4y123
  api-key: 111854312673546
  api-secret: FpFQgyAH3YYHd9tvMtoaTVZcdIM
