spring:
  application:
    name: sope ecommerce backend

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  jwt:
    secret: "284dd6c8bceeacfa2559a1ca7ef3e4c25099bea3d6a7f3e9cb2470e39a46106f1379b3b61aedbaf5299126211f663aef6c79aac2fc3913752b5ae63e06c7a592="
    expiration: 900000
    refresh-expiration: 604800000

  datasource:
    url: jdbc:postgresql://localhost:5432/sope
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 2000ms
  #      cluster:
  #        nodes:

  cache:
    type: redis
    redis:
      default-ttl: 600 # 10 minutes
      cache-ttls:
        users: 300 # 5 minutes
        products: 1800 # 30 minutes

  redis:
    timeout: 2s # connection timeout
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-total: 100
        max-idle: 50
        min-idle: 10
        max-wait: 1s
        test-on-borrow: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0
    default-schema: public
    schemas: public
    locations: classpath:db/migration
    table: flyway_schema_history

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
    org.springframework.data.redis: DEBUG
    io:
      lettuce:
        core=DEBUG:

server:
  port: 8082
  tomcat:
    max-part-count: 50
    max-part-header-size: 2048

api:

cloudinary:
  cloud-name: dybo8zd4y123
  api-key: 111854312673546
  api-secret: FpFQgyAH3YYHd9tvMtoaTVZcdIM
