spring:
  application:
    name: sope ecommerce backend

  config:
    import: optional:file:.env[.properties]

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash

  datasource:
    url: jdbc:postgresql://localhost:5432/sope?TimeZone=Asia/Ho_Chi_Minh
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 2s
      lettuce:
        pool:
          max-total: 100
          max-idle: 50
          min-idle: 10
          max-wait: 1s
      cluster:
        nodes:

  cache:
    type: redis
    redis:
      default-ttl: 10m
      cache-ttls:
        users: 5m
        products: 30m
        GOSHIP_ADDRESSES: 7d

  jackson:
    polymorphic:
      package: com.sope.sope_ecommerce_backend.model.


  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 1.0
    default-schema: public
    schemas: public
    locations: classpath:db/migration
    table: flyway_schema_history

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

app:
  jwt:
    secret: '284dd6c8bceeacfa2559a1ca7ef3e4c25099bea3d6a7f3e9cb2470e39a46106f1379b3b61aedbaf5299126211f663aef6c79aac2fc3913752b5ae63e06c7a592='
    header: Authorization
    prefix: Bearer
    expires-in-minutes: 60
    refresh-expires-in-days: 14
    clock-skew-second: 60
    rotate-on-refresh: true
    reuse-detection: true
    expiration: 900000
    refresh-expiration: 604800000
  refresh-token:
    enabled: true
    header: X-Refresh-Token
    prefix: Refresh
    expires-in-minutes: 60
    clock-skew-second: 60

  security:
    user:
    name: user
    password: password
    oauth2:
    client:
      registration:
      google:
        client-id: your-google-client-id
        client-secret: your-google-client-secret
        scope: profile, email

cors:
  allowed-origins: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-headers: Content-Type, Authorization, X-Requested-With
  exposed-headers: Content-Disposition
  allow-credentials: true
  max-age: 3600

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
    org.springframework.data.redis: DEBUG
    io:
      lettuce:
        core=DEBUG:

server:
  port: 8082
  address: 0.0.0.0
  tomcat:
    max-part-count: 50
    max-part-header-size: 2048



jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}


payment-gateway:
  vnpay:
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    secret-key: 4F3B2D1C6A7E8B9A0D1C2E3F4A5B6C7D
    api-url:
    return-url: http://localhost:8082/api/v1/payment/webhook/vnpay
    vnp-version: 2.1.0
    vnp-command: pay
    vnp_tmn-code: 2QXUI4J4


  momo:
    partner-code: MOMO
    endpoint: https://test-payment.momo.vn/v2/gateway/api
    return-url: http://localhost:3000/payment-status
    ipn-url:  https://5dec006a5639.ngrok-free.app/api/payments/webhook/momo
    access-key: F8BBA842ECF85
    secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
    request-type: captureWallet


shipping-unit:
  goship:
    base-url: https://sandbox.goship.io/api/v2
    auth-token: ${GOSHIP_AUTH_TOKEN}
    client-id: 200
    client-secret: ${GOSHIP_CLIENT_SECRET}


api:

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


web:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:5000"
      - "http://localhost:3000"
      - "http://localhost:3001"
      - "http://10.19.82.225:3000"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowed-headers: "*"
    exposed-headers:
      - "Authorization"
      - "Content-Type"
    allowed-credentials: true
    max-age: 3600



livekit:
  url: "http://localhost:7880"
  api:
    key: "devkey"
    secret: "devsecret"
