name: CI/CD pipeline for Backend Service

on:
  push:
    branches: [feature/api-product]

env:
  DOCKER_IMAGE: hoangson3000/api-product
  DOCKER_TAG: latest

jobs:
  build:
    name: Build Backend Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .env.properties in classpath
        run: |
          mkdir -p src/main/resources
          echo "jwt.private-key=${{ secrets.JWT_PRIVATE_KEY }}" > src/main/resources/env.properties
          echo "jwt.public-key=${{ secrets.JWT_PUBLIC_KEY }}" >> src/main/resources/env.properties
          echo "jwt.expiration=${{ secrets.JWT_EXPIRATION }}" >> src/main/resources/env.properties
          echo "jwt.refresh-expiration=${{ secrets.JWT_REFRESH_EXPIRATION }}" >> src/main/resources/env.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hoangson3000
          password: dckr_pat_bAGoptTuF6dRJNueqzpyKjd68iA

      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t $DOCKER_IMAGE:$DOCKER_TAG .
          docker push $DOCKER_IMAGE:$DOCKER_TAG

      - name: Copy necessary files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 3.0.183.247
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "compose.yml"
          target: "~/api-product"

  deploy:
    name: Deploy Backend Service
    runs-on: ubuntu-latest
    needs: ["build"]

    steps:
      - name: Deploy Backend Service
        uses: appleboy/ssh-action@master
        with:
          host: 3.0.183.247
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Moving to dir to deployment..."
            cd ~/api-product

            echo "Creating network (if not exists)..."
            echo "Currently, we re-use customer-network"
            docker network create customer-network || true

            echo "Stopping old container if exists..."
            docker-compose -f compose.yml stop api-product || true
            docker-compose -f compose.yml rm -f api-product || true

            echo "Pulling latest image..."
            docker-compose -f compose.yml pull api-product || true

            echo "Starting new container with correct name..."
            docker-compose -f compose.yml up -d --remove-orphans

            echo "Deployment completed!"
